export const FETCH_USERS_REQUESTED = "FETCH_USERS_REQUESTED";
export const FETCH_USERS = "FETCH_USERS";

export const FETCH_TODOS = "FETCH_TODOS";
export const FETCH_TODOS_REQUESTED = "FETCH_TODOS_REQUESTED";

export const CREATE_COMMENT = "CREATE_COMMENT";
export const CREATE_COMMENT_REQUESTED = "CREATE_COMMENT_REQUESTED";

export const POST_COMMENT = "POST_COMMENT";
export const POST_COMMENT_REQUESTED = "POST_COMMENT_REQUESTED";
